### PR TITLE
Use WorDBless

### PR DESCRIPTION
**Pull request by szepeviktor**
I'm no developer!!
Please help me fix `$this->assertTrue(current_theme_supports('post-thumbnails'));`

### CODE REVIEW

**Comment by szepeviktor** [comment]
@jarednova Could you help me here with one small advice?

**Comment by szepeviktor** [comment]
Dear Viktor!
Read the public docs!
https://developer.wordpress.org/reference/functions/add_theme_support/#post-thumbnails

**Comment by szepeviktor** [comment]
Did not help :(

**Comment by szepeviktor** [comment]
As far as my debugging goes `StarterSite::theme_supports()` is not called.
Maybe `after_setup_theme` is not fired?

**Comment by szepeviktor** [comment]
`did_action('after_setup_theme')` in the constructor returns `1`

**Comment by jarednova** [comment]
Just checked out WordBless, very cool! Let me see if I can get this up locally and figure out what's giving us the problem ...

**Comment by szepeviktor** [comment]
Maybe because of https://github.com/Automattic/wordbless/issues/27

**Comment by jarednova** [comment]
@szepeviktor I similarly narrowed things down to that place where it (seems) that the `after_theme_setup` hook is not triggered. It's supposed to occur on each page load: https://developer.wordpress.org/reference/hooks/after_setup_theme/

So the question here: is each test a page load? Does it even matter? Shouldn't this still execute and have the theme support function loaded?

**Comment by szepeviktor** [comment]
Everything would be okay if there would be no `switch_theme()` in the test setup function.

**Comment by jarednova** [comment]
I just disabled it, but still hit the error? If you're seeing that removing it works, please push so we can check it out!

**Comment by szepeviktor** [comment]
> do_action( 'after_setup_theme' );

My "solution" is to fire that action manually.

The other could be to activate Starter Theme in `bootstrap.php`

**Comment by jarednova** [comment]
very very nice!

**Pull request merged**
