### PR TITLE
Cleaned up theme (for my taste), with a kind of dependency manager

### PR DESCRIPTION
**Pull request by DevNIX**

### CODE REVIEW

**Comment by DevNIX** [comment]
Should add a brand new composer.json and put https://github.com/thomasgriffin/TGM-Plugin-Activation as a require?

**Comment by jarednova** [comment]
thanks @DevNIX! I'll review and get back to you soon

**Comment by DevNIX** [comment]
You're welcome! I would love to contribute oftenly to some open source project, and I feel that I could do something useful here.

I have several ideas, but if you find that they doesn't fit to your project I could fork it with a new name, if you don't mind :smile:

**Comment by dzienisz** [comment]
what is going on with this pull request?

**Comment by DevNIX** [comment]
Wow I forgot this! 😂

**Comment by jarednova** [comment]
@dzienisz @DevNIX thanks for the PR and reminder. The changes here (like adding TGM activation) might make total sense for your and other workflows, but I want to keep this theme as un-opinionated as possible. The tests are also important to preserve, but it's a good notion that these probably don't need to be distributed in the WP.org repo.

If there are some details in here that you think are worth taking a second look at, please re-submit the PR! Smaller > bigger when it comes to changes so we can focus on specific improvement/changes and get those into the repo

**Pull request closed without merging**
